### ISSUE TITLE
Create method for filtering

### ISSUE THREAD

**Issue by jayjacobs** [vz-risk/verisr#2]
Probably want to create some type of standard "filter" variable.  Maybe a list where the first level is either "or" or "and" (zero of more of each) and then under that is a data frame, matrix or vector containing an enum and value to filter on.  The value should be able to be a regex (e.g. "victim.industry", "^54").

The purpose is so the filter can be created once and passed around for each query.

Along those lines, maybe we create the filter once with a "setfilter" kind of thing, that will return an object that gets passed in as a filter.

**Comment by gdbassett** [comment]
closing since we do this with dplyr verbs consistently now. (and the dataframe is a tibble rather than data.table)

**Comment by gdbassett** [comment]
(yes I'm doing issue clean up on the saturday before thanksgiving.)
