### ISSUE TITLE
json2veris not working

### ISSUE THREAD

**Issue by pelekhs** [vz-risk/verisr#21]
Hello, 

When running the initial proposed analysis code:

library(verisr)
data('industry2', package='verisr')
vcdb.dir <- "../VCDB/data/json/"
if (interactive()) { # show progress bar if the session is interactive
  vcdb <- json2veris(vcdb.dir, schema="../VCDB/vcdb-merged.json", progressbar=TRUE)
} else {
  vcdb <- json2veris(vcdb.dir, schema="../VCDB/vcdb-merged.json")  
}

I keep getting this error:

Error in `[[<-.data.frame`(`*tmp*`, "ftype", value = "file") : 
  replacement has 1 row, data has 0

Thanks in advance!

**Comment by gdbassett** [comment]
sorry, we updated the file structure in VCDB but forgot to update the code here.  replace the line `vcdb.dir <- "../VCDB/data/json/"` with `vcdb.dir <- "../VCDB/data/json/validated/".  (note this must be run from within the VCDB directory after cloning the repo - https://github.com/vz-risk/VCDB).  I have updated the readme with the correct directory. Thank you for bringing this to our attention.

(Also, json2veris will now give a more informative answer when on json is found in the input.)
